name: Build Web App
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
       
    - uses: NuGet/setup-nuget@v1.0.2
    - run: nuget restore BuscaCep.sln
     

   # - name: Setup MSBuild Path
   #   uses: sinhorinho/Setup-MSBuild@v1

 
   # - name: Build and Publish Web App
   #   run: msbuild SimpleFrameworkApp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
   # - name: Upload Artifact
   #   uses: actions/upload-artifact@v1.0.0
   #   with:
   #     name: published_webapp
   #     path: bin\Release\Publish
